server:
  port: 8080

spring:
    datasource:
        url: jdbc:h2:file:~/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
