server:
  port: 8081

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
  queue: gamification_multiplication_queue
  anything:
    routing-key: multiplication.*
